#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/nullmailer
  chown nobody:nogroup /var/log/nullmailer

  exec chpst -u nobody:nogroup svlogd -tt /var/log/nullmailer
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?P<msg>.+?)\\s*$"
fi
